name: Web Test

on:
  push:

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2

      - name: checkout the code
        uses: actions/checkout@v3

      - name: Set JDK with maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn test -Pwebtest --file pom.xml
