name: Web Test

on:
  push:
    branches:
      - main
      - 'test/**'

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start selenoid
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome;firefox
          last-versions: 1

      - name: Check Selenoid has been started
        continue-on-error: true
        run: curl http://localhost:4444/status

      - name: checkout the code
        uses: actions/checkout@v3

      - name: Set JDK with maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn test -Pwebtest --file pom.xml
